spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studycafe_kiosk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: studycafe_kiosk
    password: 0608
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug